### ISSUE TITLE
Github repo description incorrect

### ISSUE THREAD

**Issue by jalessio** [gruntwork-io/module-asg-public#1]
I noticed that the Github repo description is incorrect for this repo. It refers to `module-ecs` instead of `module-asg`:
![screen shot 2018-02-06 at 4 51 12 pm](https://user-images.githubusercontent.com/178680/35892421-0c3ec0c4-0b5e-11e8-8ab9-016c040213b2.png)

**Comment by brikis98** [comment]
You have a good eye. Another copy/paste bug. Fixed now, thanks!
